# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

no_of_zeros = 0
pointer = 50
file = open('input.txt', 'r')
for cur in file:
  if cur.startswith('L'):
    pointer -= int(cur[1:])
    #print(pointer)
  else:
    pointer += int(cur[1:])
    #print(pointer)
  pointer = pointer%100
  if pointer == 0:
    no_of_zeros += 1
print(no_of_zeros)
file.close()