# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

import math

points = []
with open("input.txt") as f:
    for line in f:
        points.append(tuple(map(int, line.strip().split(","))))

n = len(points)

distances = []

for i in range(n):
    x1, y1, z1 = points[i]
    for j in range(i+1, n):
        x2, y2, z2 = points[j]
        d = ((x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2) ** (1/2)
        distances.append((d, i, j))

distances.sort(key=lambda x: x[0])

parent = list(range(n))
size = [1] * n

def find(x):
    while x != parent[x]:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x

def union(a, b):
    ra = find(a)
    rb = find(b)
    if ra == rb:
        return

    if size[ra] < size[rb]:
        ra, rb = rb, ra
    parent[rb] = ra
    size[ra] += size[rb]

for k in range(1000):
    _, i, j = distances[k]
    union(i, j)

final_sizes = {}

for i in range(n):
    r = find(i)
    final_sizes[r] = final_sizes.get(r, 0) + 1

sizes_sorted = sorted(final_sizes.values(), reverse=True)

answer = sizes_sorted[0] * sizes_sorted[1] * sizes_sorted[2]
print(answer)