# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

from functools import reduce

with open('input.txt', 'r') as file:

  data = []

  for line in file:
    data.append(list(reversed(line.strip('\n'))))

  count = 0

  cur_data = []

  for i in range(0, len(data[0])):

      cur_value = reduce(lambda x, y: x + y, [data[j][i] for j in range(len(data) - 1)], '').replace(' ', '')

      if cur_value != '':
          cur_data.append(int(cur_value))

      if data[-1][i] == '*':
        count += reduce(lambda x, y: x * y, cur_data, 1)
        cur_data = []
      elif data[-1][i] == '+':
        count += reduce(lambda x, y: x + y, cur_data, 0)
        cur_data = []

print(count)