# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

import math

points = []
with open("input.txt") as f:
    for line in f:
        points.append(tuple(map(int, line.strip().split(","))))

n = len(points)

distances = []

for i in range(n):
    x1, y1, z1 = points[i]
    for j in range(i+1, n):
        x2, y2, z2 = points[j]
        d = ((x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2) ** (1/2)
        distances.append((d, i, j))

distances.sort(key=lambda x: x[0])

parent = list(range(n))
size = [1] * n
components = n

def find(x):
    while x != parent[x]:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x

def union(a, b):
    ra = find(a)
    rb = find(b)
    if ra == rb:
        return False

    if size[ra] < size[rb]:
        ra, rb = rb, ra
    parent[rb] = ra
    size[ra] += size[rb]
    return True


last_i = last_j = None

for d, i, j in distances:
    merged = union(i, j)
    if merged:
        components -= 1
        if components == 1:
            last_i, last_j = i, j
            break

xprod = points[last_i][0] * points[last_j][0]
print(xprod)