# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

no_of_zero_points = 0
pointer = 50

with open('input.txt', 'r') as file:
    for cur in file:
        old_pointer = pointer

        if cur.startswith('L'):
            delta = -int(cur[1:])
        else:
            delta = int(cur[1:])

        no_of_zero_points += abs(delta) // 100

        rem = abs(delta) % 100
        if rem > 0:
            if delta > 0:
                if old_pointer + rem >= 100:
                    no_of_zero_points += 1
            else:
                if 1 <= old_pointer <= rem:
                    no_of_zero_points += 1

        pointer = (old_pointer + delta) % 100

print(no_of_zero_points)