# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

with open('input.txt', 'r') as file:

  data = []

  for line in file:

    data.append(list(line.strip('\n')))

count = 1

start_index = data[0].index('S')

cur_data = set([start_index])

cur_data_count = {start_index:1}

for j in range(1, len(data)):

  line = data[j]

  indexes = [i for i in cur_data if line[i] == '^']

  count += sum([cur_data_count[i] for i in indexes])

  for i in indexes:

    cur_data.discard(i)

    if i > 0:
      cur_data.add(i-1)
      cur_data_count[i-1] = cur_data_count.get(i-1, 0) + cur_data_count[i]

    if i < len(line)-1:
      cur_data.add(i+1)
      cur_data_count[i+1] = cur_data_count.get(i+1, 0) + cur_data_count[i]

    cur_data_count.pop(i)

print(count)