# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

list_of_joltage = []
with open('input.txt', 'r') as file:
  for line in file:
    first_max = '0'
    second_max = '0'
    for i in range(0, len(line) - 2):
      if line[i] > first_max:
        second_max = line[i+1]
        first_max = line[i]
      elif line[i] > second_max:
        second_max = line[i]
    if second_max < line[-2]:
      second_max = line[-2]
    list_of_joltage.append(int(first_max + second_max))
#print(list_of_joltage)
print(sum(list_of_joltage))