# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

list_of_joltage = []
with open('input.txt', 'r') as file:
  for line in file:
    line = line.strip()
    max = line[:12]
    for i in range(12, len(line)):
      #print(line[i])
      max = max + line[i]
      for j in range(0, 12):
        if max[j] < max[j + 1]:
          max = max[:j] + max[j+1:]
          break
      max = max[:12]
      #print(max)
    list_of_joltage.append(int(max))
#print(list_of_joltage)
print(sum(list_of_joltage))