# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

with open('input.txt', 'r') as file:
  data = file.read()
  parts = data.strip().split("\n\n")
  ranges_raw = parts[0].splitlines()

  ranges = []
  for r in ranges_raw:
      a, b = map(int, r.split("-"))
      ranges.append((a, b))

  ranges.sort()
  merged = []
  for start, end in ranges:
      if not merged or start > merged[-1][1]:
          merged.append([start, end])
      else:
          merged[-1][1] = max(merged[-1][1], end)

  count = 0

  for a, b in merged:
      count += b - a + 1

print(count)