# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

from functools import reduce

with open('input.txt', 'r') as file:

  data = []

  for line in file:
    data.append(line.strip().split())

  for i in range(len(data) - 1):
    data[i] = list(map(int, data[i]))

  count = 0

  for i in range(0, len(data[0])):

      if data[-1][i] == '*':
        count += reduce(lambda x, y: x * y, [data[j][i] for j in range(len(data) - 1)], 1)
      else:
        count += reduce(lambda x, y: x + y, [data[j][i] for j in range(len(data) - 1)], 0)

print(count)