# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

def is_repeated(num, len_of_num):
  return num[:len_of_num // 2] == num[len_of_num // 2:]

list_of_invalid_id = []
with open('input.txt', 'r') as file:
  for line in file:
    list_of_ranges = line.split(',')
    list_of_ranges = [[int(y) for y in x.split('-')] for x in list_of_ranges]
    for i in list_of_ranges:
      for j in range(i[0], i[1] + 1):
        num = str(j)
        len_of_num = len(num)
        if len_of_num % 2 == 0 and is_repeated(num, len_of_num):
          list_of_invalid_id.append(j)
    #print(list_of_ranges)
print(sum(list_of_invalid_id))