# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

from functools import reduce

with open('input.txt', 'r') as file:

  data = []

  for line in file:

    data.append(list(line.strip('\n')))

  count = 0

  cur_data = set([data[0].index('S')])

  for j in range(1, len(data)):

    line = data[j]

    indexes = [i for i in cur_data if line[i] == '^']

    count += len(indexes)

    for i in indexes:
      cur_data.discard(i)

      if i > 0:
        cur_data.add(i-1)

      if i < len(line)-1:
        cur_data.add(i+1)

print(count)