# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kNcgIu6oXVwRmrHzrI92QAJOSzMkOq0
"""

def check_is_valid_roll(three_line_window, roll):
  count = 0
  if three_line_window[1][roll] == '@':
    count = -1
  for i in [roll-1, roll, roll+1]:
    for j in [0, 1, 2]:
      if i >= 0 and i < len(three_line_window[j]) and three_line_window[j][i] == '@':
        count += 1
        if count > 3:
          return False
  if three_line_window[1][roll] == '@':
    return True
  else:
    return False

no_of_rolls_accessible = 0
with open('input.txt', 'r') as file:

  file_dup = []

  for line in file:
    file_dup.append(line.strip())

  rolls_moved = True

  while rolls_moved:
    rolls_moved = False
    first_line = file_dup[0]
    three_line_window = [len(first_line) * '.', len(first_line) * '.', first_line]

    for line_i in range(1, len(file_dup)):
      line = file_dup[line_i]
      three_line_window[0] = three_line_window[1]
      three_line_window[1] = three_line_window[2]
      three_line_window[2] = line.strip()
      #print(three_line_window)

      for i in range(0, len(three_line_window[1])):
        if check_is_valid_roll(three_line_window, i):
          file_dup[line_i - 1] = file_dup[line_i - 1][:i] + '.' + file_dup[line_i - 1][i+1:]
          no_of_rolls_accessible += 1
          rolls_moved = True

    three_line_window = three_line_window[1:]

    three_line_window.append(len(first_line) * '.')

    for i in range(0, len(three_line_window[1])):
        if check_is_valid_roll(three_line_window, i):
          file_dup[-1] = file_dup[-1][:i] + '.' + file_dup[-1][i+1:]
          no_of_rolls_accessible += 1
          rolls_moved = True

print(no_of_rolls_accessible)